source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Folders_Example', :exclusive => true do
  pod 'Folders', :path => '../'
end

target 'Folders_Tests', :exclusive => true do
  pod 'Folders', :path => '../'

  
end
