source 'https://github.com/CocoaPods/Specs.git'

target 'Folders_Example', :exclusive => true do
  pod 'Folders', :path => '../'
end

target 'Folders_Tests', :exclusive => true do
  pod 'Folders', :path => '../'

  
end
